[[constraint]]
  branch = "master"
  name = "github.com/dghubble/go-twitter"

[[constraint]]
  branch = "master"
  name = "github.com/dghubble/oauth1"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-nntp"

[prune]
  go-tests = true
  unused-packages = true
