name: docker

on:
  push:
    tags: '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: docker
        run: |
          TAG=$(echo $GITHUB_REF | perl -F/ -anle 'print $F[2]')
          docker build -t docker.pkg.github.com/skaji/raku-cpan-new/raku-cpan-new:$TAG .
          echo '${{ secrets.GITHUB_TOKEN }}' | docker login docker.pkg.github.com -u skaji --password-stdin
          docker push docker.pkg.github.com/skaji/raku-cpan-new/raku-cpan-new:$TAG
