name: ghcr-push

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build and push
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}
          docker build -t ghcr.io/skaji/raku-cpan-new:$IMAGE_TAG .
          echo $CR_PAT | docker login ghcr.io -u skaji --password-stdin
          docker push ghcr.io/skaji/raku-cpan-new:$IMAGE_TAG
